name: DeepSeek-R1-Distill-Qwen-32B-bnb-4bit
type: gradio-space
sdk: gradio

metadata:
  space_id: Chris4K/DeepSeek-R1-Distill-Qwen-32B-bnb-4bit
  original_url: https://huggingface.co/spaces/Chris4K/DeepSeek-R1-Distill-Qwen-32B-bnb-4bit

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"
